### ISSUE TITLE
Verify force computation

### ISSUE THREAD

**Issue by romerojosh** [RSE-Cambridge/qe-gpu#7]
Current modifications to force computation have been tested for only Ausurf testcase so far. Once modifications are complete, need to verify that force computation is correct for other supported cases and/or fix accordingly.

**Comment by maxcuda** [comment]
Force computation is still giving the wrong results when using multiple pools.
The GPU version for Ausurf with nk=2 reports:
     Total force =     **0.658727**     Total SCF correction =     0.005478
while the CPU version reports:
     Total force =     0.077225     Total SCF correction =     0.006173

With a single pool, both versions report similar forces.
     Total force =     0.077113     Total SCF correction =     0.005554 (GPU)
     Total force =     0.076734     Total SCF correction =     0.003279 (CPU)

**Comment by maxcuda** [comment]
Nevermind, I was grepping old log files.
With the latest version of the code, it is correct:

 Total force =     0.077084     Total SCF correction =     0.005104 (4 GPUs, 2 pools)
 Total force =     0.077174     Total SCF correction =     0.005478 (8 GPUs, 2 pools)

**Comment by fspiga** [comment]
As reported in #6, something is odd with forces. Various outputs here: https://goo.gl/ADwjgv

I doubt is related to restart because the differences are present also when restart is not used, see ` out.full.CPU` versus `out.full.GPU`

**Comment by fspiga** [comment]
I am running various tests, it seems the major differences are due to the ionic contribution (routine `force_ew`). I am running few more tests, summarize and report. Running CPU-only takes lot of time.......

**Comment by fspiga** [comment]
I run multiple tests with multiple versions of the code, CPU versus GPU versus 6.1 release versus SVN. All tests running using 8 MPI and K80. It is irrelevant the GPU because the problem is in the CPU code. 

All outputs are here: https://goo.gl/PT2kJx

Short description:
- `out.full.CPU.QE-6.1` = official QE v6.1 run on CPU
- `out.full.CPU.QE-GPU-0.2`= official QE-GPU 0.2 run on CPU
- `out.full.GPU.QE-GPU-0.2`= official QE-GPU 0.2 run on GPU
- `out.full.CPU.QE-GPU-head` = latest QE-GPU from repository run on CPU
- `out.full.GPU.QE-GPU-head` = latest QE-GPU from repository run on CPU
- `out.full.CPU.QE-GPU-7284a3b` = QE-GPU cloned at 7284a3b run on CPU
- `out.full.CPU.QE-GPU-adc83dd` = QE-GPU cloned at adc83dd run on CPU
- `out.full.CPU.QE-SVN` = latest official QE from SVN repository run on CPU

Based on the outputs, the `force_ew` is the one that screw the results. A good output contains these values: 
```
     The ionic contribution  to forces
     atom    1 type  1   force =    -0.10851895    0.02942679  120.39273474
     atom    2 type  1   force =    -0.10844750   -0.01347715  120.36119064
     atom    3 type  1   force =    -0.10210451    0.03453155  120.46182671
     atom    4 type  1   force =    -0.10206669   -0.00851605  120.43020538
     atom    5 type  1   force =    -0.03919614    0.03588368  120.49366194
     atom    6 type  1   force =    -0.03919285   -0.00718124  120.46202622
     atom    7 type  1   force =    -0.01430631    0.03498352  120.49853630
     atom    8 type  1   force =    -0.01430150   -0.00806903  120.46690637
     atom    9 type  1   force =     0.03254969    0.03498528  120.49571813
     atom   10 type  1   force =     0.03254404   -0.00806662  120.46408849
```

A bad one looks like this:
```
     The ionic contribution  to forces
     atom    1 type  1   force =     4.04830126    1.38270855  125.57367332
     atom    2 type  1   force =    -0.48855011    3.30404934  119.50222638
     atom    3 type  1   force =     2.51357155    4.91185328  124.05848316
     atom    4 type  1   force =    -4.28176676   -4.78846453  124.06154928
     atom    5 type  1   force =    -5.36752996    5.21860069  118.20841387
     atom    6 type  1   force =    -3.83208354   -5.46070200  118.53109744
     atom    7 type  1   force =     1.81056179    7.03569181  119.24280196
     atom    8 type  1   force =     0.69223261    3.04887420  124.39886669
     atom    9 type  1   force =     4.37768998   -0.64000733  124.25651107
     atom   10 type  1   force =    -1.88762759    1.98932073  123.88446928
```

We have a point in time a version of QE-GPU (hash adc83dd) that compiled for CPU returns the right results. After it is broken, I haven't identified exactly where. Since the problem appears already in before I started to align other part of the code to v6.1 (hash 7284a3b is already wrong), I suspect it is not related to various changes to other part of the code. The problem has between adc83dd and 7284a3b.

**Important**: GPU path always returns correct results.  

A visual summary of all the test:
<img width="400" alt="summary_qe-gpu_issue7" src="https://user-images.githubusercontent.com/2418857/28498411-bc2bfe86-6f94-11e7-9e64-98c45978924f.png">

**Note for the future**: The latest SVN version of QE returns lot of values slightly different than QE v6.1. I suspect some bug fixes have been pushed in the main code, when we will align to the next release of QE, previous outputs of v6.1 or earlier versions may not be relevant anymore.

**Comment by maxcuda** [comment]
The error was in OpenMP path in force_ew and force_corr.
@fspiga  to verify that the latest commit fixes the issue.

**Comment by fspiga** [comment]
Yes, it works. The problem was in `force_ex.f90` OpenMP. My commit c3aebecb51ac8bf8d6d2ec36e0a79cf375533319 restores OpenMP on both files.
